version: 1.0.{build}

branches:
  only:
    - main

image:
  - Visual Studio 2019

configuration: Release

build_script:
  - ps: nuget restore CrudBot.sln
  - msbuild CrudBot.sln /p:Configuration=Release

test_script:
  - dotnet test CrudBot.Main/CrudBot.Main.csproj --configuration Release
