name: .NET CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.x'

    - name: Restore dependencies
      run: dotnet restore CrudBot.sln

    - name: Build
      run: dotnet build --configuration Release CrudBot.sln

    - name: Test
      run: dotnet test --configuration Release --no-build CrudBot.sln
