name: .NET CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.x'

    - name: Restore dependencies
      run: |
        nuget restore CrudBot.sln

    - name: Build
      run: |
        msbuild CrudBot.sln /p:Configuration=Release

    - name: Debug Info
      run: |
        echo "Current directory: $(pwd)"
        echo "Contents of the repository: $(ls -a)"

